INSERT INTO EMPLOYEE (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, PHONE, BIRTH_DATE, JOB_TITLE, DEPARTMENT,
                      LOCATION, START_DATE, MANAGER_REPORTING, CREATION_DATE, LAST_UPDATE_DATE)
VALUES (1, 'Gopal', 'Shrestha', 'gshrestha1@gmail.com', '1234567890', CURRENT_DATE, 'FSD', 'Engineering', 'USA',
        CURRENT_DATE, 'Manager', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
